---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-slv-oss-amagi-com-v1-slv
  failurePolicy: Fail
  name: vslv.kb.io
  rules:
  - apiGroups:
    - slv.oss.amagi.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - slvs
  sideEffects: None
