{{- include "slvlib.clusterrole" . | nindent 0 }}

---
{{- if not (.Values.webhook.disableAutomaticCertManagement) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slv-webhook-clusterrole
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    resourceNames: [{{ .Values.webhook.validatingWebhookConfigName }}]
    verbs: ["get", "patch","update"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["list","watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","create", "update", "delete"]
    {{- if gt (int .Values.replicas) 1 }}
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get","create","update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
    {{- end }}
{{- end }}
