{{- if not (.Values.webhook.disableAutomaticCertManagement) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.webhook.certSecretName | default "slv-webhook-server-cert"}}
  namespace: {{ .Release.Namespace }}
{{- end}}
