apiVersion: v1
kind: Service
metadata:
  labels:
    app: slv-operator
  name: {{ .Values.webhook.serviceName | default "slv-webhook-service" }}
  namespace: {{ .Release.Namespace }} 
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: slv-operator
