{{- include "slvlib.serviceaccount" . | nindent 0 }}

---

{{- if and .Values.webhook.enabled .Values.webhook.createTLSCerts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: slv-webhook-sa
  namespace: {{ .Release.Namespace }}
{{- end -}}
