{{- if and .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: slv-operator
  name: slv-operator-webhook
  namespace: {{ .Release.Namespace }} 
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: slv-operator
{{- end -}}
