apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.webhook.validatingWebhookConfigName | default "slv-operator-validating-webhook" }}
  annotations: 
    {{- toYaml .Values.webhook.validatingWebhookConfigAnnotations | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.webhook.serviceName | default "slv-webhook-service" }}
      namespace: {{ .Release.Namespace }}
      path: /validate-slv-sh-v1-slv
  failurePolicy: Fail
  name: slv-webhook-service.{{ .Release.Namespace }}.svc
  rules:
  - apiGroups:
    - slv.sh
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - slvs
  sideEffects: None
