# Configuration for the SLV Environment. This environment is responsible for being able to decrypt the SLV secrets.
slvEnvironment:
    
    # Please ensure that atleast one of ["secretBinding","k8sSecret"] are filled. 
    # SLV may not work as expected without a secret key or binding specified.

    # The secretBinding String
    secretBinding: ""

    # The name of the secret in the Kubernetes cluster that contains the secretKey or the secretBinding. 
    # The secretKey is to be put inside the key name "SecretKey".
    # (or)
    # The secretBinding is to be put inside the key name "SecretBinding". 
    # Ensure that this exists in the same namespace as the release namespace.
    k8sSecret: ""

# Configuration related to how SLV has to operate within the kubernetes cluster.
config:
  
  # The mode in which SLV should run. Possible values are: ["operator","job","cronjob"].  
  # operator - This mode is used to run SLV as a Kubernetes operator (Deployment). It will watch for changes in the SLV CRD and take action accordingly.
  # job - This mode is used to run SLV as a Kubernetes job. It will run once and exit. This mode assumes that you already have the CRDs created.
  # cronjob - This mode is used to run SLV as a Kubernetes cronjob. It will run at the specified schedule and exit. 
  mode: operator

  # Whether to enable the SLV webhook or not. 
  # This is only applicable for the operator mode. 
  # This feature is still work in progress and will be enabled in the future.
  enableWebhook: false

  # The number of replicas to be used by the deployment for SLV pods. 
  # This is only applicable when the mode is set to "operator".
  replicas: 1

  # The number of times kubernetes must retry the job in case of failure.
  # This is only applicable when the mode is set to "job" or "cronjob".
  backoffLimit: 4

  # The number of seconds after which the job must be deleted after it has finished.
  # This is only applicable when the mode is set to "job" or "cronjob".
  ttlSecondsAfterFinished: 3600

  # How frequently the CronJob has to be run.
  # This is only applicable when the mode is set to "cronjob".
  schedule: "0 * * * *" # Runs at the top of every hour

# The configuration for the SLV pod that will be run. 
# This will be shared across all modes and hence is common.
runnerConfig:
  
  # The image with tag to be used for SLV
  # You must ensure that the tag that you use is the same as Chart.Version
  # Otherwise, helm will throw an error.
  image: ghcr.io/amagioss/slv:0.8.0
  # The image pull policy.
  imagePullPolicy: IfNotPresent


  # Setting resource constraints for the operator.
  resource:
    # Resource limits 
    limits:
      cpu: "300m" 
      memory: "300Mi" 
    # Resource requests 
    requests:
      cpu: "250m" 
      memory: "250Mi" 
  
  # The labels to be set for the Deployment/CronJob/Job
  labels: {}

  # The pod Labels to be set for SLV pods.
  podLabels: {}

  # The name with which the serviceAccount has to be created and attached to the SLV pods.
  serviceAccountName: ""
