project_name: slv
builds:
  - id: slv
    binary: slv
    main: ./cli
    env:
      - CGO_ENABLED=0
    ldflags: "-X oss.amagi.com/slv.Version={{.Version}} -X oss.amagi.com/slv.commitDate={{.CommitDate}} -X oss.amagi.com/slv.fullCommit={{.FullCommit}} -X oss.amagi.com/slv.releaseURL={{.ReleaseURL}}"
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - linux_arm
      - windows_amd64
  - id: slv-operator
    binary: slv-operator
    main: ./operator/cmd
    env:
      - CGO_ENABLED=0
    ldflags: "-X oss.amagi.com/slv.Version={{.Version}} -X oss.amagi.com/slv.commitDate={{.CommitDate}} -X oss.amagi.com/slv.fullCommit={{.FullCommit}} -X oss.amagi.com/slv.releaseURL={{.ReleaseURL}}"
    goarch:
      - amd64
      - arm64
    goos:
      - linux
archives:
  - id: slv
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    builds:
      - slv
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-dev"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - builds:
      - slv
    file_name_template: '{{ .PackageName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    vendor: Amagi Media Labs
    homepage: https://oss.amagi.com/slv
    maintainer: Shibly Meeran <shibme@shib.me>
    formats:
      - apk
      - deb
      - rpm
brews:
  - ids:
      - slv
    name: slv
    homepage: "https://oss.amagi.com/slv"
    commit_author:
      name: Shibly Meeran
      email: shibme@shib.me
    repository:
      owner: amagioss
      name: homebrew-slv
      branch: main
      git:
        url: 'git@github.com:amagioss/homebrew-slv.git'
        private_key: '{{ .Env.HOMEBREW_SSH_KEY }}'
