project_name: slv
builds:
  - id: slv
    binary: slv
    main: ./cli
    env:
      - CGO_ENABLED=0
    ldflags: "-X savesecrets.org/slv.Version={{.Version}} -X savesecrets.org/slv.commitDate={{.CommitDate}} -X savesecrets.org/slv.fullCommit={{.FullCommit}} -X savesecrets.org/slv.releaseURL={{.ReleaseURL}}"
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - linux_arm
      - windows_amd64
  - id: slv-operator
    binary: slv-operator
    main: ./operator/cmd
    env:
      - CGO_ENABLED=0
    ldflags: "-X savesecrets.org/slv.Version={{.Version}}"
    goarch:
      - amd64
      - arm64
    goos:
      - linux
archives:
  - id: slv
    format: zip
    builds:
      - slv
snapshot:
  name_template: "{{ incpatch .Version }}-dev"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - builds:
      - slv
    vendor: SaveSecrets
    homepage: https://savesecrets.org/slv
    maintainer: Shibly Meeran <shibme@shib.me>
    formats:
      - apk
      - deb
      - rpm
brews:
  - ids:
      - slv
    name: slv
    homepage: "https://savesecrets.org/slv"
    commit_author:
      name: Shibly Meeran
      email: shibme@shib.me
    repository:
      owner: savesecrets
      name: homebrew-tap
      branch: main
      git:
        url: 'git@github.com:savesecrets/homebrew-tap.git'
        private_key: '{{ .Env.HOMEBREW_SSH_KEY }}'
