builds:
  - id: k8slv
    binary: k8slv
    main: ./k8s/cmd
    env:
      - CGO_ENABLED=0
    ldflags: "-X github.com/amagimedia/slv.Version={{.Version}}"
    goarch:
      - amd64
      - arm64
    goos:
      - linux
