apiVersion: k8s.amagi.com/v1
kind: SLV
metadata:
  name: supercat
slvSecrets:
  name: SLV_VSS_AFLAAJABAFLAACP4YIPAJV63DTDKCMPZHWIQRUJJJZRSA7KOO3VLDDOC7YAFKOD7ADLPBZ74PIXL5PYZIETEVWICTLAAWUYCBECUR2LSMHOXY2HEBKLTDFBQWCKRDFPYB7S5G7Z4J56PDLD25AS5GH7F76TADN2P4EWYSEJ4XGTPSBINKSWFVRUOSQHMPIRBB4PA6ZY357DUHZXU4ZZFAMFI7CYQ
slvConfig:
  publicKey: SLV_VPK_AEAVMAAJ7TBB4BGX3MOMNIJR7E6ZCCGRFFHGGID5JZ3OVMMNYL7AAVJYP4
  wrappedKeys:
    - SLV_EWK_AFCQAJABAFCQBC4M2C6WCF3L73OE6EDB5F77YNSWS54SV3PBR4VBAQ3JCP5ZJASZAAJGRI244SFFNTE5UH5OPB62AYYZU53KSRKVKGLUHXY2CXH6FNVUQVMAPD2EPYFVXWLILNXKVRK5TCNI3CTSZQVAPIOACDQPL4C2RV4MXDWAZECNGVNZOTR26KUVIAKLVQBPV5QW5NESXMLWVQOTPDNG5EEE4CIUVY3WJKWIVSLWQBUGWHY6RTWBCU3FODLFVIKLU
