{{- if eq .Values.config.mode "operator" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slv-k8s-operator-clusterrole
rules:
  - apiGroups: ["slv.oss.amagi.com"]
    resources: ["slvs"]
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - "create"
      - "get"
      - "list"
      - "update"
      - "delete"
      - "watch"
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs:
      - "get"
      - "create"
      - "update"
{{- end}}
---
{{ if eq .Values.config.mode "job" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slv-k8s-job-role
rules:
  - apiGroups: ["slv.oss.amagi.com"]
    resources: ["slvs"]
    verbs:
      - "get"
      - "list"
      - "update"
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - "get"
      - "create"
      - "list"
      - "update"
      - "delete"
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs:
      - "get"
      - "create"
      - "update"
{{- end}}
---
{{ if eq .Values.config.mode "cronjob" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slv-k8s-cronjob-role
rules:
  - apiGroups: ["slv.oss.amagi.com"]
    resources: ["slvs"]
    verbs:
      - "get"
      - "list"
      - "update"
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - "get"
      - "create"
      - "list"
      - "update"
      - "delete"
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs:
      - "get"
      - "create"
      - "update"
{{- end}}
