{{- if eq .Values.config.mode "cronjob" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: slv-k8s-cronjob
  namespace: {{ .Release.Namespace }}
  labels:
    app: slv-k8s-cronjob
    {{- with .Values.runnerConfig.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: {{ .Values.config.schedule | default "0 * * * *" }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.config.ttlSecondsAfterFinished | default 0 }}
      template:
        metadata:
          name: slv-k8s-cronjob
          namespace: {{ .Release.Namespace }}
          labels:
            app: slv-k8s-cronjob
            {{- with .Values.runnerConfig.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          containers:
          {{- include "slv.container" . | nindent 12 }}
          restartPolicy: Never
          serviceAccountName: {{ .Values.runnerConfig.serviceAccountName | default "slv-sa" }}
      backoffLimit: {{ .Values.config.backoffLimit | default 4 }}
{{- end}}
