{{- if eq .Values.config.mode "job" }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  slv-job
  namespace: {{ .Release.Namespace }}
  labels:
    app: slv-job
    {{- with .Values.runnerConfig.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ttlSecondsAfterFinished: {{ .Values.config.ttlSecondsAfterFinished | default 3600 }}
  template:
    metadata:
      name: slv-job
      namespace: {{ .Release.Namespace }}
      labels:
        app: slv-job
        {{- with .Values.runnerConfig.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      {{- include "slv.container" . | nindent 8 }}
      restartPolicy: Never
      serviceAccountName: {{ .Values.runnerConfig.serviceAccountName | default "slv-sa" }}
  backoffLimit: {{ .Values.config.backoffLimit | default 4 }}
{{- end}}
