name: Build Main Branch

on:
  push:
    branches:
      - main

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: build -f k8s/.goreleaser.yml --clean
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Release Branch Version of K8s Controller
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          file: k8s/Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/k8slv:${{ github.ref_name }}