name: Release

on:
  push:
    tags:
      - '*'

jobs:

  slv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: GoReleaser - Release SLV
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_SSH_KEY: ${{ secrets.HOMEBREW_SSH_KEY }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Release SLV Image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      - name: Release SLV K8s Operator Image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          file: operator/Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/operator:latest
            ghcr.io/${{ github.repository }}/operator:${{ github.ref_name }}
