name: Release

on:
  push:
    tags:
      - '*'

jobs:

  release-cli:
    name: Release CLI & Library
    runs-on: ubuntu-latest
    steps:
      - name: Setting SLV Version
        run: echo "SLV_VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: GoReleaser - Release SLV
        run: |
          docker run --rm \
          -w /workspace \
          -v $PWD:/workspace \
          -e GITHUB_TOKEN \
          -e HOMEBREW_SSH_KEY \
          ghcr.io/goreleaser/goreleaser-cross:latest release \
          -f .goreleaser-slv-cli.yaml \
          --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_SSH_KEY: ${{ secrets.HOMEBREW_SSH_KEY }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Release SLV Image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.SLV_VERSION }}
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest

  release-k8s:
    name: Release SLV K8s Images
    runs-on: ubuntu-latest
    steps:
      - name: Setting SLV Version
        run: echo "SLV_VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: GoReleaser - Release SLV
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: build -f .goreleaser-slv-k8s.yaml --clean
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Release SLV K8s Operator Image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          file: k8s/Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/slv-k8s-operator:${{ env.SLV_VERSION }}
            ghcr.io/${{ github.repository }}/slv-k8s-operator:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}/slv-k8s-operator:latest
      - name: Release SLV K8s Job Image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          file: k8s/job/Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/slv-k8s-job:${{ env.SLV_VERSION }}
            ghcr.io/${{ github.repository }}/slv-k8s-job:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}/slv-k8s-job:latest
